export const FALLBACK_EXAMPLES = [
  {
    emailFrom: 'jan.kowalski@acme.com',
    emailSubject: 'Should we migrate to Drizzle ORM?',
    emailBody: "Hey, I've been looking at Drizzle vs Prisma for the new service. What do you think? Can we chat before standup?",
    labels: ['internal', 'needs-reply'],
    priority: 'medium',
    needsReply: true,
    summary: 'Teammate asks for opinion on ORM choice before standup.',
  },
  {
    emailFrom: 'no-reply@linear.app',
    emailSubject: 'You were assigned: PLAT-99 — Hotfix: auth token leak in prod',
    emailBody: 'Priority: Urgent. Sprint: current. Due: today. Description: Auth tokens are leaking in error responses on /api/login. Fix immediately.',
    labels: ['automated', 'urgent'],
    priority: 'high',
    needsReply: false,
    summary: 'Urgent task assignment to hotfix auth token leak in production.',
  },
  {
    emailFrom: 'recruiter@hireme.io',
    emailSubject: 'Amazing CTO opportunity — $500k+ equity',
    emailBody: 'Hi! Your GitHub repos are incredible. I have a once-in-a-lifetime CTO role at a funded startup. 15 min call?',
    labels: ['spam'],
    priority: 'low',
    needsReply: false,
    summary: 'Unsolicited recruiter outreach for a CTO position.',
  },
  {
    emailFrom: 'notifications@github.com',
    emailSubject: '[org/repo] Issue #88: Memory leak in worker pool',
    emailBody: '@you was mentioned in org/repo#88. "Can you take a look at this? Seems related to the pool changes you merged last week."',
    labels: ['github', 'automated', 'needs-reply'],
    priority: 'medium',
    needsReply: true,
    summary: 'GitHub issue mention requesting investigation of a memory leak.',
  },
  {
    emailFrom: 'billing@stripe.com',
    emailSubject: 'Invoice #INV-2026-0312 for Stripe Billing',
    emailBody: 'Your monthly invoice for $249.00 is ready. Payment will be charged to Visa ending 1234 on Apr 1.',
    labels: ['billing', 'automated'],
    priority: 'low',
    needsReply: false,
    summary: 'Monthly Stripe billing invoice notification.',
  },
];
